services:
  mkdocs:
    image: squidfunk/mkdocs-material:latest
    hostname: mkdocs
    command: "serve --dev-addr=0.0.0.0:8000"
    volumes:
      - .:/docs
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
