site_name: PHAIDRA
theme:
  name: material
  palette:
    primary: white
  logo: /assets/img/logo.svg
  favicon: /assets/img/logo.svg
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.path

extra_css:
  - assets/css/tweaks.css
  - assets/css/tailwind.min.css

