site_name: PHAIDRA
repo_url: https://github.com/phaidra/phaidra
repo_name: phaidra/phaidra
theme:
  name: material
  palette:
    primary: white
  logo: /assets/img/logo.svg
  favicon: /assets/img/logo.svg
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.path

extra_css:
  - assets/css/tweaks.css
  - assets/css/tailwind.min.css

plugins:
  - search
  - privacy
